/***************************************************************************

	FILE:		example.h

	AUTHOR:		Eric Chasanoff

	REVISIONS:	08.15.96	Written

	DESCRIPTION:
			Example program definitions.

	DISCLAIMER:

		Raster Builders Inc. and Eric Chasanoff make no representations
		about the correctness or suitability of this software for
		any purpose. It is provided without express or implied
		warranty.

***************************************************************************/

#ifndef _EXAMPLE_DEFINED_
#define _EXAMPLE_DEFINED_

#define	IDM_EXIT			100
#define	IDM_RESET			108
#define	IDM_COM1			110
#define	IDM_COM2			112
#define	IDM_COM3			114
#define	IDM_COM4			116
#define	IDM_BACKLIGHT		118
#define	IDM_LIGHTS			120
#define	IDM_BW				122
#define	IDM_NEGATIVE		124
#define	IDM_INPUT			126

#endif

/* end of file : example.h */
